@baseUrl = http://localhost:3333

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibHVpei5qIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzM4OTE2MTA_dj00Iiwic3ViIjoiZmUxNzJjZjktM2M4ZC00MGIwLWIwZjYtMDBhZGM3OTI4NTk4IiwiaWF0IjoxNjg0NDQwODQxLCJleHAiOjE2ODcwMzI4NDF9.g11ohJGvN_AGQPLdDEpqAYMM3UqI1KzYRituEoUR6CU

### 
GET {{ baseUrl }}/users 
Content-Type: application/json


###  Get All Memories
GET {{ baseUrl }}/memories 
Content-Type: application/json
Authorization: Bearer {{ token }}

###
 
###  Get One Memory By ID
GET {{ baseUrl }}/memories/4e796340-3218-4d25-9306-779092b0de6b  
Content-Type: application/json

###

###  Create Memory
POST {{ baseUrl }}/memories 
Content-Type: application/json

{
    "content": "test",
    "coverUrl": "sfs",
    "isPublic": "1"
}
 
###  Update Memory
PUT  {{ baseUrl }}/memories/2e52bb8d-9618-4a38-a3c1-92e2ffc93e06
Content-Type: application/json

{
    "content": "oi",
    "coverUrl": "sfs",
    "isPublic": "1"
}


###  Getting User from Giuthub
POST  {{ baseUrl }}/register
Content-Type: application/json

{
    "code": "f2ff172243e5b65b3965"
}

###  Getting User from Giuthub
POST  {{ baseUrl }}/register
Content-Type: application/json

{
    "code": "4d525cb21409f03ebc59"
}